-- 코드를 작성해주세요
-- 테이블: ECOLI_DATA
-- 컬럼: ID(대장균 개체의 ID), PARENT_ID(부모 개체의 ID), SIZE_OF_COLONY(분화되어 나온 날짜),
-- DIFFERENTATION_DATE(분화되어 나온 날짜), GENOTYPE(개체의 형질)
-- 최초의 PARENT_ID IS NULL

SELECT COUNT(ID) as COUNT
FROM ECOLI_DATA
WHERE BIN(GENOTYPE) LIKE '%101' OR BIN(GENOTYPE) LIKE '%100' OR BIN(GENOTYPE) LIKE '%001' OR BIN(GENOTYPE) = 1